[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moderngl>=5.12.0",
    "numpy>=2.4.0",
    "pygame>=2.6.1",
    "pyrr>=0.10.3",
    "requests>=2.32.5",
]
